pull_request_rules:
  # TODO: Change greenkeeper for Synk
  # - name: Automatically merge Greenkeeper PRs on CI success
  #   conditions:
  #     - status-success=Test
  #     - status-success=ci/codesandbox
  #     - status-success=greenkeeper/verify
  #     - author=greenkeeper[bot]
  #   actions:
  #     merge:
  #       method: merge
  - name: Automatically merge Greg's PRs on CI success
    conditions:
      - status-success=Test
      - status-success=ci/codesandbox
      - 'status-success=LGTM analysis: JavaScript'
      - 'status-success=security/snyk (GregBrimble)'
      - -draft
      - status-success=codeclimate
      - author=GregBrimble
    actions:
      merge:
        method: merge
  - name: Delete head branch after merging PR
    conditions: []
    actions:
      delete_head_branch: {}
